Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"

  config.vm.hostname = "vm-ubuntuu"

  config.vm.network "private_network", ip: "192.168.56.21"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Overleaf"
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.synced_folder "./logs", "/home/vagrant/logs"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    apt-get install -y \
      curl \
      git \
      ca-certificates \
      apt-transport-https \
      software-properties-common


    curl -fsSL https://get.docker.com | sh

    usermod -aG docker vagrant
    apt-get install -y docker-compose-plugin
    apt-get install -y htop vim net-tools unzip
  SHELL

end